version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: me_transfer_db
    restart: always
    environment:
      # Docker Compose leerá estas variables de tu archivo .env automáticamente
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: